name: atrial-fibrillation-detection
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy=1.21.0
  - pandas=1.3.0
  - scikit-learn=0.24.2
  - tensorflow=2.6.0
  - keras=2.6.0
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - jupyterlab=3.1.0
  - pyyaml=5.4.1
  - scipy=1.7.1
  - tqdm=4.62.3
  - pip:
      - complex-valued-tensorflow==0.1.0
      - tensorflow-addons==0.14.0