default_config:
  wandb_api_key: "e25db435fb197ebd4e9df6caa2262e2f9f4571af"
  run_name: "Full DataSet"
  model:
    architecture: "Complex_ResNet-18_GADF_iGADF"
  training:
    batch_size: 128
    learning_rate: 0.001
    epochs: 30
    optimizer: "Adam"
    loss_function: "BinaryCrossEntropy"
  data:
    input_shape: [3, 224, 224]
    data_dir: "/home/stud1/Desktop/nidhi/Diptiman/GAF_DATA2"
    num_classes: 1
    augmentation: true
    dataloader:
      num_workers: 24
      pin_memory: true
      drop_last_train: true
      shuffle_train: true
      shuffle_val: false
      shuffle_test: false
      prefetch_factor: 3
      persistent_workers: true
      use_cache: true
      cache_size: 25000
  logging:
    log_dir: "./logs"
    save_model: true
    model_save_path: "./saved_models/Complex_Resnet-18_GADF_iGADF"
