default_config:
  wandb_api_key: "e25db435fb197ebd4e9df6caa2262e2f9f4571af"
  run_name: "default_run"
  model:
    architecture: "AlexNet"
  training:
    batch_size: 32
    learning_rate: 0.001
    epochs: 10
    optimizer: "Adam"
    loss_function: "BinaryCrossEntropy"
  data:
    input_shape: [3, 128, 128]
    data_dir: "/home/prasad/Desktop/datas2"
    augmentation: true
    dataloader:
      num_workers: 4
      pin_memory: true
      drop_last_train: true
      shuffle_train: true
      shuffle_val: false
      shuffle_test: false
  logging:
    log_dir: "./logs"
    save_model: true
    model_save_path: "./saved_models"
