default_config:
  wandb_api_key: "e25db435fb197ebd4e9df6caa2262e2f9f4571af"
  run_name: "Chunked DataSet"
  model:
    architecture: "ResNet-18"
  training:
    batch_size: 16
    learning_rate: 2e-6
    epochs: 30
    optimizer: "Adam"
    loss_function: "BinaryCrossEntropy"
  data:
    input_shape: [3, 224, 224]
    data_dir: "/home/prasad/Desktop/datas2"
    num_classes: 1
    augmentation: true
    dataloader:
      num_workers: 6
      pin_memory: true
      drop_last_train: true
      shuffle_train: true
      shuffle_val: false
      shuffle_test: false
      prefetch_factor: 2
      persistent_workers: true
      use_cache: true
      cache_size: 1000
  logging:
    log_dir: "./logs"
    save_model: true
    model_save_path: "./saved_models"
